# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  confee-postgres-data:
    driver: local

  # Redis Data
  confee-redis-data:
    driver: local

services:
  # Postgres (9.5)
  postgres:
    image: ambientum/postgres:9.6
    container_name: confee-postgres
    volumes:
      - confee-postgres-data:/var/lib/postgresql/data
    ports:
      - "5438:5438"
    environment:
      - POSTGRES_PASSWORD=confee
      - POSTGRES_DB=confee
      - POSTGRES_USER=confee

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: confee-redis
    command: --appendonly yes
    volumes:
      - confee-redis-data:/data
    ports:
      - "6379:6379"

  # Confee API
  api:
    image: ambientum/php:7.0-caddy
    container_name: confee-api
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - postgres
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: confee-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - postgres
      - cache
